name: Changelog

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'test-server.sh'
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  changelog:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install conventional-changelog
        run: npm install -g conventional-changelog-cli

      - name: Create empty changelog (if missing)
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          fi

      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit and push changelog
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "chore: update changelog" || echo "No changes to commit"
          git push origin HEAD
